// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpeojzobekiqqufhbhjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZW9qem9iZWtpcXF1ZmhiaGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4Njg1NTEsImV4cCI6MjA1NzQ0NDU1MX0.JtX9VPvVyWFeBzQ1mmiaA6QZkkAWfAAhNThy_f9bJDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);